### ISSUE TITLE
Built Fails with Missing files in JAVA

### ISSUE THREAD

**Issue by Chanthujan** [zerotier/libzt#107]
While running the following command
./build.sh host-jar

Error getting reported such as Java files are missing 

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
error: file not found: com/zerotier/libzt/*.java
Usage: javac <options> <source files>
use --help for a list of possible options
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
com/zerotier/libzt/*.class : no such file or directory
/home/chanthuj/eew_android_app/zerotier_temp_1/libzt

Contents of JAR:

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java.nio.file.NoSuchFileException: /home/chanthuj/eew_android_app/zerotier_temp_1/libzt/cache/linux-x64-jar-release/pkg/jar/*.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1239)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at jdk.jartool/sun.tools.jar.Main.list(Main.java:1500)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:380)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)

Could anyone help me on this please

**Comment by joseph-henry** [comment]
Java sources were intentionally removed pending the results of [Google V Oracle](https://en.wikipedia.org/wiki/Google_LLC_v._Oracle_America,_Inc.). We planned on dropping Java support altogether if the case went the wrong way. Now that this is cleared up new (WIP) Java sources have been added. As of this comment they build and pass a basic self-test but still need a lot of refinement, this will take place in the coming weeks.
