### ISSUE TITLE
Python3.6.8 undefined symbol: _ZN8ZeroTier12LinuxNetLinkD1Ev

### ISSUE THREAD

**Issue by DarkiT** [zerotier/libzt#180]
i'am trying to create a program to list all the nodes that are connected to my network

see below a simple code from the documentation , which doesn't work .

hereby what i've tried so far

sudo apt upgrade

sudo apt update

tried to install a different version on libzt

no good

here is the code:

import libzt

# ...
n = libzt.ZeroTierNode()
n.node_start()
# ...
n.net_join(0x1234567890abcdef)
# ...
client = libzt.socket(libzt.ZTS_AF_INET, libzt.ZTS_SOCK_STREAM, 0)
client.connect((remote_ip, remote_port))
and here is the error :

Traceback (most recent call last):

File "/home/igalc/barilan/PythonScrtips/ProjectHomework/test/test8.py", line 1, in <module>

import libzt

File "/usr/local/lib/python3.9/dist-packages/libzt/__init__.py", line 1, in <module>

from .libzt import *

File "/usr/local/lib/python3.9/dist-packages/libzt/libzt.py", line 13, in <module>

from . import _libzt

ImportError: /usr/local/lib/python3.9/dist-packages/libzt/_libzt.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN8ZeroTier12LinuxNetLinkD1Ev

**Comment by tralph3** [comment]
I have the exact same error on Arch Linux Python 3.8.

**Comment by tralph3** [comment]
Some attention on this please? I'm trying to develop an application and I can't even get started since I can't import this module in any way.

**Comment by P-PPPP** [comment]
Same Occured On python 3.9

**Comment by P-PPPP** [comment]
please use old version
```
pip uninstall libzt
pip install libzt==1.4.2
```
