### ISSUE TITLE
unable to use compiled jar

### ISSUE THREAD

**Issue by 04041b** [zerotier/libzt#265]
When I tried to import and compile my own project, the error "Exception in thread "main" java.lang.UnsatisfiedLinkError: no zt in java.library.path: " occur. When I try to use the way in #59, it errored with 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int com.zerotier.sockets.ZeroTierNative.zts_init()'
        at com.zerotier.sockets.ZeroTierNative.zts_init(Native Method)
        at com.zerotier.sockets.ZeroTierNative.<clinit>(ZeroTierNative.java:28)
        at com.zerotier.sockets.ZeroTierNode.start(ZeroTierNode.java:32)
```

**Comment by Jus-Leg** [comment]
> solved, https://docs.zerotier.com/sockets not updated

How we're you able to fix it?

**Comment by joseph-henry** [comment]
> > solved, https://docs.zerotier.com/sockets not updated
> 
> How we're you able to fix it?

I just tried the instructions in the example folder here: https://github.com/zerotier/libzt/tree/main/examples/java and it worked just fine on Linux. What platform are you on?
