### ISSUE TITLE
Java Demo:  UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sebouh137** [zerotier/libzt#59]
After compiling, if I run the following command (to run the example app)

java -cp examples/java/src/main/java:lib/release/macos-x86_64/zt.jar -Djava.library.path=lib/release/macos-x86_64/ ExampleApp

I get the following error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int com.zerotier.libzt.ZeroTier.init()'
	at com.zerotier.libzt.ZeroTier.init(Native Method)
	at com.zerotier.libzt.ZeroTier.<clinit>(ZeroTier.java:59)
	at ExampleApp.main(ExampleApp.java:43)

**Comment by sebouh137** [comment]
Never mind.  I found the correct instructions for running this example in the comments of in dist.sh
